config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#home'
  get '/register', to: 'users#new'
  post 'users', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'sessions', to: 'sessions#create'

  get '/logout', to: 'sessions#destroy'

  resources :pairs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pair.rb
class Pair < ApplicationRecord
  belongs_to :requestor_user, class_name: "User"  #dafault foreignn key is user_id, this one is requestor_user_id
  belongs_to :respondor_user, class_name: "User", optional: true
  validates :title, length: {in: 10 ..100}
  validates :description, presence: true
  validate :different_respondor

  def different_respondor
    if self.respondor_user == self.requestor_user
      self.errors.add(:respondor_user)
    end
  end

  def accepted_by(user)
    # if user == self.requestor_user
      # self.errors.add(:respondor_user, " can not pair with yourself")
      # self.errors.add(:respondor_user) #also work
      # return false
      # self.valid?
    # else
      self.update(respondor_user: user)
      # byebug
    # end
  end

  def accepted?
    true if respondor_user
  end

  def self.by_status(status)
    case status
    when :open
      where(respondor_user: nil)
    when :active
      where.not(respondor_user: nil)
    end
  end

  def topic
    ActiveSupport::Deprecation.warn("Please user 'title' over 'topic'." )
    self.title
  end

end #end of class

app/models/user.rb
class User < ApplicationRecord
  has_many :pair_requests, class_name: "Pair", foreign_key: "requestor_user_id"
  has_many :pair_responses, class_name: "Pair", foreign_key: "respondor_user_id"

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user
  def home
  end

  private
  def current_user
    if session[:current_user_id]
      @current_user ||= User.find(session[:current_user_id])
    end
  end

  def login(user)
    session[:current_user_id] = user.id
  end

  def logged_in?
    current_user ? true : false
  end

  def authenticaton_required
    if !logged_in?
      redirect_to "/login", alert: "To pair up, Please Login!"
    end
  end
end

app/controllers/pairs_controller.rb
class PairsController < ApplicationController
  before_action :authenticaton_required
  # before_action :logged_in?
  def new
    @pair = Pair.new
  end

  def index
    @pairs = Pair.all
    @open_pairs = Pair.by_status(:open)
  end

  def show
    @pair = Pair.find_by(id: params[:id])
    # raise @pair.inspect
  end

  def update
    # byebug
    @pair = Pair.find_by(id: params[:id])
    # if @pair.update(respondor_user: current_user)
    # byebug
    if @pair.accepted_by(current_user)
      redirect_to @pair
    else
      render :show
    end
  end

  def create
    @pair = Pair.create(title: params[:title], description: params[:description], requestor_user_id: current_user.id)
    # @pair.requestor_user_id = current_user.id
    if @pair.save
      redirect_to "/pairs"
    else
      render :new
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @session = User.new
  end

  def create
    # byebug
    @user = User.find_by(email: params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      # raise "Hello".inspect
      # session[:current_user_id] = @user.id  #replace it with private method login(user)
      login(@user)
      redirect_to '/'
    else
      # flash[:notice] = "Warning: No user found"
      # redirect_to "/login", alert: "Alert: Please check user name or password"
      redirect_to "/login", notice: "Notice: check user name or password"
    end
  end

  def destroy
    reset_session
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    # render plain: "hello"
    @user = User.new
    if session[:current_user_id]
      redirect_to '/', notice: "User already login"
    end
  end

  def create
    # byebug
    # raise "hello".inspect
    # @user = User.create(email: params[:email]) #form_tag params format is different with form_for
    @user = User.create(email: params[:user][:email], password: params[:user][:password])
    if @user.save
      redirect_to "/login"
    else
      render :new
    end
  end

end #end of class

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pairs_helper.rb
module PairsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.html.erb
<!-- <h3>Welcome to Find a Pair Home Page</h3>
<h5>The best way to find someone to pair program with</h5> -->

<main role="main" page="home">
  <div class="jumbotron text-center">
    <div class="container">
      <h1 class="display-3">Never Program Alone</h1>
      <p class="lead">Stuck with something? Well, you are not alone anymore. On Find a Pair, you can request to pair with someone of help someone else work on their project</p>
      <hr class="my-4">
      <p>Looking for more elegant approach to feature? Wodnering how something works?</p>
      <!-- <p class="lead">
        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
      </p> -->

      <button type="button" onclick="window.location.href = '/pairs/new';" class="btn btn-primary">Request a Pair</button>

      <form class="" style="display: inline;" action="/paris/new" method="get">
        <input type="submit" class="btn btn-primary" name="" value="Request Pair Up">
      </form>

      <form class="" style="display: inline;" action="/paris/new" method="get">
        <button type="submit" class="btn btn-primary" name="" value="">Pair Up </button>
      </form>

      <button onclick="window.location.href = '/pairs';" class="btn btn-secondary">Browser Pairs Requests</button>

      <a href="/pairs" class="btn btn-secondary" >All Requests</a>

    </div>

  </div>

  <section class="newest">
    <h3>Newsest Pair Requests</h3>
    <div class="row">
      <div class="card col-md mx-2">
        <div class="card-body">
          <h4 class="card-title">Understanding Webpacker</h4>
          <h6 class="card-subtitle mb-2 text-muted">Henry</h6>
          <p class="card-text">Need some help understand Webpacker works with Rails.</p>
          <a href="#" class="card-link">Learn More</a>
          <a href="#" class="card-link">Pair With</a>
        </div>
      </div>

      <div class="card col-md mx-2">
        <div class="card-body">
          <h4 class="card-title">Card title</h4>
          <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="card-link">Card link</a>
          <a href="#" class="card-link">Another link</a>
        </div>
      </div>

      <div class="card col-md mx-2">
        <div class="card-body">
          <h4 class="card-title">Card title</h4>
          <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="card-link">Card link</a>
          <a href="#" class="card-link">Another link</a>
        </div>
      </div>

    </div>
  </section>

</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FindAPair</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="/">Find a Pair</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <%= link_to "Open Pairs List", pairs_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New Pair", new_pair_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to_unless_current "Login", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Register", register_path, class: "nav-link" %>
          </li>


          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
  </header>

<% if false %>
    <nav>
      <section>
        <%= link_to_unless_current "Home", root_path %>
        <%= link_to_unless_current "Open Pairs List", pairs_path %>
        <%= link_to_unless_current "New Pair", new_pair_path %>
      </section>

      <section class="utility">
        <% if session[:current_user_id] %>
          <p>You are logged in as : <%= @current_user.email %> | <a href="/logout">Logout</a></p>
        <% else %>
          <%= link_to_unless_current "Login", login_path %> |
          <%= link_to_unless_current "Register", register_path %>
        <% end %>
      </section>
    </nav>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/pairs/index.html.erb
<h3>All Pairs List/Index</h3>

<ol>
  <% @pairs.each do |p| %>
  <li><%= link_to "#{p.topic} from #{p.requestor_user.email}", pair_path(p) %></li>
  <% end %>
</ol>

<h3>Open Pairs</h3>

<ol>
  <% @open_pairs.each do |p| %>
      <li><%= link_to "#{p.title} from #{p.requestor_user.email}", pair_path(p) %></li>
  <% end %>
</ol>

app/views/pairs/new.html.erb
<h3>Find/Request a pair | Pair new form</h3>
<%= form_tag("/pairs") do %>
  <p>
    <%= label_tag "title", "Title" %>

    <% if @pair.errors[:title].first %>
      <p class="validation_errors">Warning:<%= "#{@pair.errors.full_messages_for(:title).first}" %></p>
    <% end %>

    <%= text_field_tag "title" %>
  </p>

  <p>
    <%= label_tag "description", "Description" %>

    <% if @pair.errors[:description].first %>
      <p class="validation_errors"><%= "#{@pair.errors.full_messages_for(:description).first}" %></p>
    <% end %>

    <%= text_area_tag "description" %>
  </p>

  <%= submit_tag %>
<% end %>

app/views/pairs/show.html.erb
<% if @pair.errors[:respondor_user].first %>
<p class="validation_errors"><%= @pair.errors.full_messages_for(:respondor_user).first %></p>
<% end %>

<div class="card col-md mt-5">
  <div class="card-body">
    <h4 class="card-title">Title:<%= @pair.title %></h4>
    <h6 class="card-subtitle mb-2 text-muted">Requestor: <%= @pair.requestor_user.email %></h6>
    <p class="card-text">Description: <%= @pair.description %></p>
    <p class="card-text">Accepted By: <%= @pair.respondor_user ? @pair.respondor_user.email : "None"  %></p>
    <a href="#" class="card-link">Learn More</a>
    <%= link_to "Pair With", pair_path(@pair), method: "patch", class: "card-link" %>
  </div>
</div>
<hr>

<hr>

<% if false %>
  <h3>Pair Show Page</h3>
  <h4>Pair Topic/Title: <%= @pair.topic %></h4>
  <h4>Pair Description: <%= @pair.description %></h4>
  <h5>Requested by: <%= @pair.requestor_user.email %></h5>

  <% if @pair.accepted? %>
  <h5>Accepted by: <%= @pair.respondor_user.email %></h5>
  <% else %>
  <%= form_for(@pair) do |t| %>

  <% if @pair.errors[:respondor_user].first %>
  <p class="validation_errors"><%= @pair.errors.full_messages_for(:respondor_user).first %></p>
  <% end %>
  <%= t.submit "Accept this Pair" %>
  <% end %>
  <% end %>
<% end %>

app/views/users/new.html.erb
<div class="card bg-light mt-5">
  <article class="card-body mx-auto" style="max-width: 400px;">
    <h4 class="card-title mt-3 text-center">New User Registration</h4>
    <%= form_for(@user, url: users_path(@user)) do |f| %>

      <div class="form-group input-group">
        <div class="input-group-prepend">
          <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
        </div>

        <%= f.email_field :email, class: "form-control", placeholder: "Email Address" %>

        <div class="input-group-append">
          <span class="input-group-text"> <i class="fa fa-envelope">@email.com</i> </span>
        </div>

      </div>

      <% if @user.errors[:password][0] %>
        <p class="validation_errors">Validations Error:<%= @user.errors.full_messages_for(:password).first %></p>
      <% end %>

      <div class="form-group input-group">
        <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>

        <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
      </div>

      <div class="form-group">
        <%= f.submit "Create Account", class: "btn btn-primary btn-block" %>
      </div>

      <p class="text-center">Have an account? <a href="/login">Log In</a> </p>

    <% end %>

  </article>

</div>